import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# ------------------ PAGE CONFIG ------------------
st.set_page_config(
    page_title="Diabetic Retinopathy Detection",
    layout="centered"
)

# ------------------ CUSTOM CSS ------------------
st.markdown("""
<style>
body {
    background-color: #0b0f1a;
}
.main {
    background-color: #0b0f1a;
}
h1 {
    color: #ffffff;
    text-align: center;
    font-weight: 700;
}
h3 {
    color: #ffffff;
}
p, li {
    color: #f1f1f1 !important;
    font-size: 16px;
}
.card {
    background-color: #151a2e;
    padding: 20px;
    border-radius: 14px;
    margin-bottom: 20px;
}
.footer {
    text-align: center;
    color: #cccccc;
    margin-top: 40px;
    font-size: 14px;
}
.upload-box {
    border: 2px dashed #4da6ff;
    padding: 20px;
    border-radius: 12px;
}
</style>
""", unsafe_allow_html=True)

# ------------------ LOAD MODEL ------------------
@st.cache_resource
def load_model():
    return tf.keras.models.load_model("saved_models/model_trained.h5")

model = load_model()

# ------------------ CLASS LABELS ------------------
class_labels = {
    0: ("No DR", "Your eyes look healthy. No disease detected."),
    1: ("Mild DR", "Small eye problem detected. Please consult a doctor."),
    2: ("Moderate DR", "Eye damage found. Doctor visit is very important."),
    3: ("Severe DR", "Serious eye problem. Immediate medical attention needed.")
}

# ------------------ IMAGE PREPROCESS ------------------
def preprocess_image(image):
    image = image.resize((224, 224))
    img_array = np.array(image) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

# ------------------ HEADER ------------------
st.markdown("<h1>Diabetic Retinopathy Detection</h1>", unsafe_allow_html=True)

st.markdown("""
<p style="text-align:center;">
This application uses a <b>Convolutional Neural Network (CNN)</b> to analyze retinal images
and detect the severity level of <b>Diabetic Retinopathy</b>.
</p>
""", unsafe_allow_html=True)

# ------------------ DR LEVELS ------------------
st.markdown("""
<div class="card">
<h3>🩺 DR Severity Levels</h3>
<ul>
<li><b>No DR</b> – Healthy retina</li>
<li><b>Mild DR</b> – Early-stage damage</li>
<li><b>Moderate DR</b> – Noticeable damage</li>
<li><b>Severe DR</b> – High risk of vision loss</li>
</ul>
</div>
""", unsafe_allow_html=True)

# ------------------ IMAGE UPLOAD ------------------
st.markdown("<h3>📤 Upload Retinal Image</h3>", unsafe_allow_html=True)

uploaded_file = st.file_uploader(
    "Upload eye image (JPG, JPEG, PNG)",
    type=["jpg", "jpeg", "png"]
)

# ------------------ PREDICTION ------------------
if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")

    st.markdown("<div class='card'>", unsafe_allow_html=True)
    st.image(image, caption="Uploaded Retinal Image", use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

    with st.spinner("🔍 Analyzing image, please wait..."):
        img_input = preprocess_image(image)
        prediction = model.predict(img_input)
        predicted_class = np.argmax(prediction)
        confidence = np.max(prediction) * 100

        label, simple_msg = class_labels[predicted_class]

    # ------------------ RESULT ------------------
    st.markdown("""
    <div class="card">
    <h3>📊 Diagnosis Result</h3>
    </div>
    """, unsafe_allow_html=True)

    st.success(f"**Detected Condition:** {label}")
    st.info(f"**Message for Patient:** {simple_msg}")
    st.warning(f"**Prediction Confidence:** {confidence:.2f}%")

    st.markdown("""
    <p style="color:#dddddd;">
    ⚠ This result is generated by AI and should not be considered a final medical diagnosis.
    Always consult an eye specialist.
    </p>
    """, unsafe_allow_html=True)

# ------------------ FOOTER ------------------
st.markdown("""
<div class="footer">
© 2026 | Diabetic Retinopathy Detection System<br>
Developed by <b>Ali Raza</b>
</div>
""", unsafe_allow_html=True)
